In [1]:
import pandas as pd
import os

# Đọc file Excel
df = pd.read_csv("Hospital Wait  TIme Data.csv")

# Hiển thị 10 dòng đầu
df.head(10)

,PatientID,AgeGroup,Department,AppointmentType,InsuranceType,ArrivalMethod,VisitDate,AppointmentTime,ActualArrivalTime,CheckInTime,...,TestsToDischargeTime,TotalTimeInHospital,TotalDelayTime,ArrivalHour,ArrivalDayOfWeek,ArrivalMonth,OccupancyRateBin,ProvidersOnShiftBin,NursesOnShiftBin,StaffPatientRatioBin
0,P100000,Adult (36-60),Orthopedics,New Patient,Private,Walk-in,15-03-2024,15-03-2024 14:00,15-03-2024 13:32,15-03-2024 13:36,...,71.066667,151.750000,123.766667,13,4,3,Low,"(5.0, 7.0]","(12.0, 15.0]","(0.2, 0.3]"
1,P100001,Adult (36-60),Cardiology,Specialist Referral,Self-pay,Scheduled,1/1/2024,1/1/2024 9:45,1/1/2024 9:36,1/1/2024 9:41,...,4.500000,141.050000,128.583333,9,0,1,Medium,"(5.0, 7.0]","(12.0, 15.0]","(0.099, 0.2]"
2,P100002,Young Adult (18-35),General Surgery,Specialist Referral,Medicaid,Scheduled,19-01-2024,19-01-2024 16:15,19-01-2024 16:07,19-01-2024 16:10,...,119.933333,387.050000,376.700000,16,4,1,Very High,"(3.0, 5.0]","(6.0, 9.0]","(0.099, 0.2]"
3,P100003,Adult (36-60),Emergency,Urgent Care,NaN,Emergency,27-03-2024,27-03-2024 11:00,27-03-2024 10:59,27-03-2024 11:02,...,13.183333,37.183333,37.116667,10,2,3,Low,"(3.0, 5.0]","(2.999, 6.0]","(0.3, 0.4]"
4,P100004,Senior (61+),Cardiology,Urgent Care,Medicare,Scheduled,10/3/2024,10/3/2024 16:45,10/3/2024 16:48,10/3/2024 16:52,...,14.466667,223.083333,222.850000,16,6,3,High,"(7.0, 8.0]","(9.0, 12.0]","(0.2, 0.3]"
5,P100005,Adult (36-60),Radiology,Specialist Referral,NaN,Walk-in,29-03-2024,29-03-2024 16:00,29-03-2024 15:50,29-03-2024 15:51,...,76.066667,151.750000,141.816667,15,4,3,Medium,"(5.0, 7.0]","(6.0, 9.0]","(0.3, 0.4]"
6,P100006,Senior (61+),Obstetrics,Urgent Care,NaN,Scheduled,25-02-2024,25-02-2024 13:00,25-02-2024 13:11,25-02-2024 13:15,...,5.450000,123.033333,130.566667,13,6,2,High,"(7.0, 8.0]","(9.0, 12.0]","(0.3, 0.4]"
7,P100007,Adult (36-60),Orthopedics,Urgent Care,Medicaid,Scheduled,13-02-2024,13-02-2024 10:00,13-02-2024 09:59,13-02-2024 10:04,...,41.916667,173.600000,168.883333,9,1,2,Medium,"(5.0, 7.0]","(2.999, 6.0]","(0.3, 0.4]"
8,P100008,Senior (61+),Neurology,New Patient,Medicare,Scheduled,31-03-2024,31-03-2024 14:45,31-03-2024 14:42,31-03-2024 14:45,...,9.183333,192.916667,187.833333,14,6,3,Very High,"(5.0, 7.0]","(2.999, 6.0]","(0.2, 0.3]"
9,P100009,Senior (61+),Oncology,Urgent Care,Private,Scheduled,11/1/2024,11/1/2024 8:30,11/1/2024 8:06,11/1/2024 8:09,...,14.366667,101.716667,76.116667,8,3,1,Medium,"(5.0, 7.0]","(9.0, 12.0]","(0.3, 0.4]"

In [2]:
import pandas as pd

# Đọc file CSV
df = pd.read_csv("Hospital Wait  TIme Data.csv")

# Đếm số lượng missing từng cột và chỉ lấy cột > 0
missing_summary = df.isnull().sum()
missing_summary = missing_summary[missing_summary > 0].sort_values(ascending=False)

# Hiển thị kết quả
print("Các cột có dữ liệu thiếu:")
print(missing_summary)

Các cột có dữ liệu thiếu:
RegistrationTime             3511
RegistrationToCheckInTime    3511
RegistrationWaitTimeTime     3511
TestsOrdered                 1490
InsuranceType                 978
dtype: int64

In [3]:
df["TestsOrdered"] = df["TestsOrdered"].fillna("None")
df["InsuranceType"] = df["InsuranceType"].fillna("None")

# Kiểm tra lại số lượng missing
print(df[["TestsOrdered", "InsuranceType"]].isnull().sum())

TestsOrdered     0
InsuranceType    0
dtype: int64

In [4]:
duplicate_count = df.duplicated().sum()

print(f"Số dòng dữ liệu bị trùng: {duplicate_count}")

# Hiển thị các dòng trùng (nếu có)
duplicates = df[df.duplicated()]

if duplicate_count > 0:
    print("\nCác dòng bị trùng:")
    print(duplicates)
else:
    print("\nKhông có dòng dữ liệu trùng.")

Số dòng dữ liệu bị trùng: 0

Không có dòng dữ liệu trùng.

In [5]:
# list tất cả cột datetime của bạn
datetime_cols = [
    'VisitDate',
    'AppointmentTime',
    'ActualArrivalTime',
    'CheckInTime',
    'TriageCompleteTime',
    'ProviderStartTime',
    'ProviderEndTime',
    'TestsCompleteTime',
    'DischargeTime',
    'ArrivalDateTime'
]

# convert tất cả về datetime chuẩn
for col in datetime_cols:
    df[col] = pd.to_datetime(df[col], format='mixed', dayfirst=True, errors='coerce')

# drop dòng lỗi datetime
df = df.dropna(subset=['ActualArrivalTime', 'DischargeTime'])

# OPTIONAL: đảm bảo logic thời gian đúng
df = df[df['DischargeTime'] >= df['ActualArrivalTime']]

# convert về format thống nhất (string đẹp để Tableau đọc)
for col in datetime_cols:
    df[col] = df[col].dt.strftime('%Y-%m-%d %H:%M:%S')

# lưu file sạch
df.to_csv("clean_hospital_data.csv", index=False)

print("DONE CLEAN DATA")

DONE CLEAN DATA

In [6]:
import pandas as pd
import os

# Đọc file Excel
df = pd.read_csv("clean_hospital_data.csv")

# Hiển thị 10 dòng đầu
df.head(10)
# Số dòng, số cột
print("Kích thước dữ liệu:", df.shape)

# Chỉ lấy số dòng
print("Số dòng:", df.shape[0])

# Chỉ lấy số cột
print("Số cột:", df.shape[1])

Kích thước dữ liệu: (5000, 57)
Số dòng: 5000
Số cột: 57

In [7]:
import pandas as pd

# đọc file
df = pd.read_csv("clean_hospital_data.csv")

# convert datetime
df['ActualArrivalTime'] = pd.to_datetime(df['ActualArrivalTime'])
df['DischargeTime'] = pd.to_datetime(df['DischargeTime'])

# tạo cột ngày
df['VisitDate'] = df['ActualArrivalTime'].dt.date

hours = list(range(24))
results = []

# loop từng ngày
for date in df['VisitDate'].unique():
    df_day = df[df['VisitDate'] == date]

    for h in hours:
        hour_start = pd.Timestamp(date) + pd.Timedelta(hours=h)
        hour_end = hour_start + pd.Timedelta(hours=1)

        # 🔥 LOGIC MỚI: OVERLAP INTERVAL
        count = df_day[
            (df_day['ActualArrivalTime'] < hour_end) &
            (df_day['DischargeTime'] >= hour_start)
        ]['PatientID'].nunique()

        results.append({
            'VisitDate': date,
            'Hour': h,
            'Patients': count
        })

# dataframe kết quả
result_df = pd.DataFrame(results)

# trung bình theo giờ
avg_per_hour = result_df.groupby('Hour')['Patients'].mean().reset_index()

print(avg_per_hour)

    Hour   Patients
0      0   0.000000
1      1   0.000000
2      2   0.000000
3      3   0.000000
4      4   0.000000
5      5   0.000000
6      6   0.000000
7      7   1.758242
8      8   8.076923
9      9  13.758242
10    10  18.340659
11    11  21.098901
12    12  22.406593
13    13  22.692308
14    14  22.802198
15    15  22.747253
16    16  20.912088
17    17  15.164835
18    18   9.032967
19    19   4.285714
20    20   1.747253
21    21   0.604396
22    22   0.175824
23    23   0.032967

In [8]:
df['Hour'] = df['ActualArrivalTime'].dt.hour

arrival_volume = df.groupby('Hour')['PatientID'].nunique().reset_index()

print(arrival_volume)

    Hour  PatientID
0      7        160
1      8        575
2      9        536
3     10        551
4     11        546
5     12        579
6     13        566
7     14        542
8     15        562
9     16        377
10    17          6

In [9]:
import pandas as pd

# đọc file
df = pd.read_csv("clean_hospital_data.csv")

# convert datetime
df['ActualArrivalTime'] = pd.to_datetime(df['ActualArrivalTime'])
df['DischargeTime'] = pd.to_datetime(df['DischargeTime'])

# tạo cột Hour và Date
df['Hour'] = df['ActualArrivalTime'].dt.hour
df['Date'] = df['ActualArrivalTime'].dt.date

# nếu chưa có thì tính Total Time
df['TotalTimeInHospital'] = (
    df['DischargeTime'] - df['ActualArrivalTime']
).dt.total_seconds() / 60   # phút

# 🔥 BƯỚC 1: trung bình theo NGÀY + GIỜ
temp = df.groupby(['Date', 'Hour'])['TotalTimeInHospital'].mean().reset_index()

# 🔥 BƯỚC 2: trung bình theo GIỜ (FINAL)
avg_time = temp.groupby('Hour')['TotalTimeInHospital'].mean().reset_index()

print(avg_time)

    Hour  TotalTimeInHospital
0      7           168.263821
1      8           162.943602
2      9           169.199835
3     10           160.772174
4     11           163.756724
5     12           161.915990
6     13           160.260508
7     14           159.754875
8     15           167.079245
9     16           162.179026
10    17           244.200000

In [10]:
df.columns

Index(['PatientID', 'AgeGroup', 'Department', 'AppointmentType',
       'InsuranceType', 'ArrivalMethod', 'VisitDate', 'AppointmentTime',
       'ActualArrivalTime', 'CheckInTime', 'TriageCompleteTime',
       'ProviderStartTime', 'ProviderEndTime', 'TestsCompleteTime',
       'DischargeTime', 'TriageCategory', 'ReasonForVisit', 'TestsOrdered',
       'ConsultationNeeded', 'ProviderID', 'RoomNumber',
       'FacilityOccupancyRate', 'ProvidersOnShift', 'NursesOnShift',
       'StaffToPatientRatio', 'ArrivalDateTime', 'RegistrationTime',
       'AssignedDepartment', 'FirstSeenByNurseTime',
       'DoctorOrProcedureStartTime', 'IsRegistered', 'IsOnlineBooking',
       'BookingType', 'Year', 'Month', 'Day', 'DayOfWeek', 'IsWeekend',
       'Quarter', 'ArrivalDelayTime', 'RegistrationWaitTimeTime',
       'RegistrationToCheckInTime', 'CheckInToNurseTime',
       'NurseToTriageCompleteTime', 'TriageToProviderStartTime',
       'ConsultationDurationTime', 'ProviderEndToTestsCompleteTime',
       'TestsToDischargeTime', 'TotalTimeInHospital', 'TotalDelayTime',
       'ArrivalHour', 'ArrivalDayOfWeek', 'ArrivalMonth', 'OccupancyRateBin',
       'ProvidersOnShiftBin', 'NursesOnShiftBin', 'StaffPatientRatioBin',
       'Hour', 'Date'],
      dtype='object')

In [11]:
df['Total Waiting Time'] = (
    df['RegistrationWaitTimeTime'] +
    df['CheckInToNurseTime'] +
    df['TriageToProviderStartTime']
)
hourly_avg_wait = df.groupby('ArrivalHour')['Total Waiting Time'].mean().reset_index()
hourly_avg_wait

    ArrivalHour  Total Waiting Time
0             7           71.160569
1             8           61.943720
2             9           59.341185
3            10           56.715473
4            11           61.409942
5            12           57.891152
6            13           63.173169
7            14           61.354055
8            15           61.803856
9            16           60.242937
10           17          138.843029

In [12]:
avg_steps = {
    'Registration': df['RegistrationWaitTimeTime'].mean(),
    'CheckInToNurse': df['CheckInToNurseTime'].mean(),
    'TriageToProvider': df['TriageToProviderStartTime'].mean(),
    'Consultation': df['ConsultationDurationTime'].mean(),
    'TestsToDischarge': df['TestsToDischargeTime'].mean()
}

import pandas as pd
avg_steps_df = pd.DataFrame(list(avg_steps.items()), columns=['Stage', 'Avg Minutes'])
avg_steps_df

              Stage  Avg Minutes
0      Registration     6.033138
1    CheckInToNurse     3.176405
2  TriageToProvider    51.725690
3      Consultation    18.711503
4  TestsToDischarge    44.700077

In [13]:
import pandas as pd

# 1. Chuẩn hóa ngày (bỏ giờ)
df['Date'] = pd.to_datetime(df['VisitDate']).dt.date

# 2. Đếm số bệnh nhân mỗi ngày theo khoa
daily_counts = (
    df.groupby(['Department', 'Date'])['PatientID']
      .count()
      .reset_index(name='Daily Patients')
)

# 3. Lấy trung bình theo khoa
avg_daily_patients = (
    daily_counts.groupby('Department')['Daily Patients']
    .mean()
    .reset_index(name='Avg Patients per Day')
)

avg_daily_patients

          Department  Avg Patients per Day
0         Cardiology              5.329670
1          Emergency              5.400000
2    General Surgery              5.560440
3  Internal Medicine              5.549451
4          Neurology              5.544444
5         Obstetrics              5.285714
6           Oncology              5.888889
7        Orthopedics              5.466667
8         Pediatrics              5.791209
9          Radiology              5.433333

In [14]:
import pandas as pd

# 1. Chuẩn hóa ngày
df['Date'] = pd.to_datetime(df['VisitDate']).dt.date

# 2. Lấy ngày trong tháng (1–31)
df['Day'] = pd.to_datetime(df['VisitDate']).dt.day

# 3. Đếm số bệnh nhân mỗi ngày
daily_counts = (
    df.groupby('Date')['PatientID']
    .nunique()   # tránh duplicate
    .reset_index(name='Daily Patients')
)

# 4. Gắn lại Day
daily_counts['Day'] = pd.to_datetime(daily_counts['Date']).dt.day

# 5. Tính trung bình theo Day (1–31)
avg_by_day = (
    daily_counts.groupby('Day')['Daily Patients']
    .mean()
    .reset_index(name='Avg Patients')
)

avg_by_day

    Day  Avg Patients
0     1     57.333333
1     2     59.666667
2     3     50.000000
3     4     53.333333
4     5     53.666667
5     6     55.666667
6     7     55.000000
7     8     55.666667
8     9     53.000000
9    10     65.333333
10   11     55.666667
11   12     55.666667
12   13     57.000000
13   14     43.000000
14   15     48.333333
15   16     52.000000
16   17     57.333333
17   18     53.000000
18   19     54.333333
19   20     60.333333
20   21     52.333333
21   22     56.333333
22   23     57.000000
23   24     54.000000
24   25     52.666667
25   26     66.666667
26   27     51.333333
27   28     54.666667
28   29     58.333333
29   30     51.000000
30   31     51.000000

In [15]:
import pandas as pd

# 1. Chuẩn hóa ngày
df['Date'] = pd.to_datetime(df['VisitDate']).dt.date

# 2. Lấy thứ trong tuần
df['DayOfWeek'] = pd.to_datetime(df['VisitDate']).dt.day_name()

# 3. Đếm số bệnh nhân mỗi ngày
daily_counts = (
    df.groupby('Date')['PatientID']
    .nunique()   # tránh duplicate
    .reset_index(name='Daily Patients')
)

# 4. Gắn lại DayOfWeek
daily_counts['DayOfWeek'] = pd.to_datetime(daily_counts['Date']).dt.day_name()

# 5. Tính trung bình theo DayOfWeek
avg_by_dow = (
    daily_counts.groupby('DayOfWeek')['Daily Patients']
    .mean()
    .reset_index(name='Avg Patients')
)

# 6. Sort thứ
order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
avg_by_dow['DayOfWeek'] = pd.Categorical(avg_by_dow['DayOfWeek'], categories=order, ordered=True)
avg_by_dow = avg_by_dow.sort_values('DayOfWeek')

avg_by_dow

   DayOfWeek  Avg Patients
1     Monday     55.153846
5    Tuesday     58.230769
6  Wednesday     53.307692
4   Thursday     50.461538
0     Friday     54.692308
2   Saturday     57.000000
3     Sunday     55.769231

In [16]:
# 1. đếm provider theo từng ngày + từng hour
tmp = df.groupby(["VisitDate", "ArrivalHour"])["ProviderID"].nunique().reset_index()

# 2. lấy trung bình theo hour
result = tmp.groupby("ArrivalHour")["ProviderID"].mean().reset_index()

result.columns = ["ArrivalHourHour", "Avg_Providers"]

print(result)

    ArrivalHourHour  Avg_Providers
0                 7       1.890244
1                 8       5.879121
2                 9       5.549451
3                10       5.703297
4                11       5.681319
5                12       6.054945
6                13       5.890110
7                14       5.688889
8                15       5.802198
9                16       4.044444
10               17       1.200000

In [17]:
import pandas as pd

# đọc file
df = pd.read_csv("clean_hospital_data.csv")

# convert datetime
df['ActualArrivalTime'] = pd.to_datetime(df['ActualArrivalTime'])
df['DischargeTime'] = pd.to_datetime(df['DischargeTime'])

# tạo cột ngày + giờ
df['VisitDate'] = df['ActualArrivalTime'].dt.date
df['ArrivalHour'] = df['ActualArrivalTime'].dt.hour

# ==============================
# 🔵 1. PATIENTS IN SYSTEM
# ==============================

hours = list(range(24))
results = []

for date in df['VisitDate'].unique():
    df_day = df[df['VisitDate'] == date]

    for h in hours:
        hour_start = pd.Timestamp(date) + pd.Timedelta(hours=h)
        hour_end = hour_start + pd.Timedelta(hours=1)

        # overlap interval
        count = df_day[
            (df_day['ActualArrivalTime'] < hour_end) &
            (df_day['DischargeTime'] >= hour_start)
        ]['PatientID'].nunique()

        results.append({
            'VisitDate': date,
            'Hour': h,
            'Patients': count
        })

patients_df = pd.DataFrame(results)

# avg patients theo hour
avg_patients = patients_df.groupby('Hour')['Patients'].mean().reset_index()
avg_patients.rename(columns={'Patients': 'Avg_Patients'}, inplace=True)

# ==============================
# 🔵 2. PROVIDERS
# ==============================

tmp = df.groupby(["VisitDate", "ArrivalHour"])["ProviderID"].nunique().reset_index()

avg_providers = tmp.groupby("ArrivalHour")["ProviderID"].mean().reset_index()
avg_providers.rename(columns={
    "ArrivalHour": "Hour",
    "ProviderID": "Avg_Providers"
}, inplace=True)

# ==============================
# 🔵 3. MERGE + RATIO
# ==============================

final = pd.merge(avg_patients, avg_providers, on="Hour", how="inner")

# ratio
final["Patients_per_Provider"] = final["Avg_Patients"] / final["Avg_Providers"]

# ==============================
# 🔵 4. EXPORT FILE
# ==============================

final.to_csv("patients_vs_providers_hour.csv", index=False)

print(final)

    Hour  Avg_Patients  Avg_Providers  Patients_per_Provider
0      7      1.758242       1.890244               0.930167
1      8      8.076923       5.879121               1.373832
2      9     13.758242       5.549451               2.479208
3     10     18.340659       5.703297               3.215800
4     11     21.098901       5.681319               3.713733
5     12     22.406593       6.054945               3.700544
6     13     22.692308       5.890110               3.852612
7     14     22.802198       5.688889               4.008199
8     15     22.747253       5.802198               3.920455
9     16     20.912088       4.044444               5.170571
10    17     15.164835       1.200000              12.637363

In [18]:
import pandas as pd

# đọc file
df = pd.read_csv("clean_hospital_data.csv")

# convert datetime
df['ActualArrivalTime'] = pd.to_datetime(df['ActualArrivalTime'])
df['DischargeTime'] = pd.to_datetime(df['DischargeTime'])

# tạo cột ngày
df['VisitDate'] = df['ActualArrivalTime'].dt.date

hours = list(range(24))
results = []

# loop từng ngày
for date in df['VisitDate'].unique():
    df_day = df[df['VisitDate'] == date]

    for h in hours:
        hour_start = pd.Timestamp(date) + pd.Timedelta(hours=h)
        hour_end = hour_start + pd.Timedelta(hours=1)

        # 🔥 LOGIC MỚI: OVERLAP INTERVAL
        count = df_day[
            (df_day['ActualArrivalTime'] < hour_end) &
            (df_day['DischargeTime'] >= hour_start)
        ]['PatientID'].nunique()

        results.append({
            'VisitDate': date,
            'Hour': h,
            'Patients': count
        })

# dataframe kết quả
result_df = pd.DataFrame(results)

# trung bình theo giờ
avg_per_hour = result_df.groupby('Hour')['Patients'].mean().reset_index()

print(avg_per_hour)

    Hour   Patients
0      0   0.000000
1      1   0.000000
2      2   0.000000
3      3   0.000000
4      4   0.000000
5      5   0.000000
6      6   0.000000
7      7   1.758242
8      8   8.076923
9      9  13.758242
10    10  18.340659
11    11  21.098901
12    12  22.406593
13    13  22.692308
14    14  22.802198
15    15  22.747253
16    16  20.912088
17    17  15.164835
18    18   9.032967
19    19   4.285714
20    20   1.747253
21    21   0.604396
22    22   0.175824
23    23   0.032967

In [19]:
df.isnull().sum()

PatientID                            0
AgeGroup                             0
Department                           0
AppointmentType                      0
InsuranceType                      978
ArrivalMethod                        0
VisitDate                            0
AppointmentTime                      0
ActualArrivalTime                    0
CheckInTime                          0
TriageCompleteTime                   0
ProviderStartTime                    0
ProviderEndTime                      0
TestsCompleteTime                    0
DischargeTime                        0
TriageCategory                       0
ReasonForVisit                       0
TestsOrdered                      1490
ConsultationNeeded                   0
ProviderID                           0
RoomNumber                           0
FacilityOccupancyRate                0
ProvidersOnShift                     0
NursesOnShift                        0
StaffToPatientRatio                  0
ArrivalDateTime                   2972
RegistrationTime                  3511
AssignedDepartment                   0
FirstSeenByNurseTime                 0
DoctorOrProcedureStartTime           0
IsRegistered                         0
IsOnlineBooking                      0
BookingType                          0
Year                                 0
Month                                0
Day                                  0
DayOfWeek                            0
IsWeekend                            0
Quarter                              0
ArrivalDelayTime                     0
RegistrationWaitTimeTime          3511
RegistrationToCheckInTime         3511
CheckInToNurseTime                   0
NurseToTriageCompleteTime            0
TriageToProviderStartTime            0
ConsultationDurationTime             0
ProviderEndToTestsCompleteTime       0
TestsToDischargeTime                 0
TotalTimeInHospital                  0
TotalDelayTime                       0
ArrivalHour                          0
ArrivalDayOfWeek                     0
ArrivalMonth                         0
OccupancyRateBin                     0
ProvidersOnShiftBin                  0
NursesOnShiftBin                     0
StaffPatientRatioBin                 0
dtype: int64

In [20]:
df['InsuranceType'] = df['InsuranceType'].fillna('Unknown')

In [21]:
df['TestsOrdered'] = df['TestsOrdered'].fillna('No Test')

In [22]:
df['RegistrationTime'] = df['RegistrationTime'].fillna('No Registration')

In [23]:
time_cols = [
    'ArrivalDateTime','CheckInTime','TriageCompleteTime',
    'ProviderStartTime','ProviderEndTime',
    'TestsCompleteTime','DischargeTime',
    'FirstSeenByNurseTime','DoctorOrProcedureStartTime'
]

for col in time_cols:
    df[col] = pd.to_datetime(
        df[col],
        format='%d-%m-%Y %H:%M',  
        errors='coerce'
    )

In [24]:
df['VisitDate'] = pd.to_datetime(df['VisitDate'], format='%d-%m-%Y', errors='coerce')

df['AppointmentTime'] = pd.to_datetime(df['AppointmentTime'], format='%d-%m-%Y %H:%M', errors='coerce')

df['ActualArrivalTime'] = pd.to_datetime(df['ActualArrivalTime'],format='%d-%m-%Y %H:%M', errors='coerce')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   PatientID                       5000 non-null   object
 1   AgeGroup                        5000 non-null   object
 2   Department                      5000 non-null   object
 3   AppointmentType                 5000 non-null   object
 4   InsuranceType                   5000 non-null   object
 5   ArrivalMethod                   5000 non-null   object
 6   VisitDate                       5000 non-null   datetime64[ns]
 7   AppointmentTime                 0 non-null      datetime64[ns]
 8   ActualArrivalTime               5000 non-null   datetime64[ns]
 9   CheckInTime                     0 non-null      datetime64[ns]
 10  TriageCompleteTime              0 non-null      datetime64[ns]
 11  ProviderStartTime               0 non-null      datetime64[ns]
 12  ProviderEndTime                 0 non-null      datetime64[ns]
 13  TestsCompleteTime               0 non-null      datetime64[ns]
 14  DischargeTime                   5000 non-null   datetime64[ns]
 15  TriageCategory                  5000 non-null   object
 16  ReasonForVisit                  5000 non-null   object
 17  TestsOrdered                    5000 non-null   object
 18  ConsultationNeeded              5000 non-null   bool
 19  ProviderID                      5000 non-null   object
 20  RoomNumber                      5000 non-null   object
 21  FacilityOccupancyRate           5000 non-null   float64
 22  ProvidersOnShift                5000 non-null   int64
 23  NursesOnShift                   5000 non-null   int64
 24  StaffToPatientRatio             5000 non-null   float64
 25  ArrivalDateTime                 0 non-null      datetime64[ns]
 26  RegistrationTime                5000 non-null   object
 27  AssignedDepartment              5000 non-null   object
 28  FirstSeenByNurseTime            0 non-null      datetime64[ns]
 29  DoctorOrProcedureStartTime      0 non-null      datetime64[ns]
 30  IsRegistered                    5000 non-null   int64
 31  IsOnlineBooking                 5000 non-null   int64
 32  BookingType                     5000 non-null   object
 33  Year                            5000 non-null   int64
 34  Month                           5000 non-null   object
 35  Day                             5000 non-null   int64
 36  DayOfWeek                       5000 non-null   object
 37  IsWeekend                       5000 non-null   bool
 38  Quarter                         5000 non-null   int64
 39  ArrivalDelayTime                5000 non-null   float64
 40  RegistrationWaitTimeTime        1489 non-null   float64
 41  RegistrationToCheckInTime       1489 non-null   float64
 42  CheckInToNurseTime              5000 non-null   float64
 43  NurseToTriageCompleteTime       5000 non-null   float64
 44  TriageToProviderStartTime       5000 non-null   float64
 45  ConsultationDurationTime        5000 non-null   float64
 46  ProviderEndToTestsCompleteTime  5000 non-null   float64
 47  TestsToDischargeTime            5000 non-null   float64
 48  TotalTimeInHospital             5000 non-null   float64
 49  TotalDelayTime                  5000 non-null   float64
 50  ArrivalHour                     5000 non-null   int64
 51  ArrivalDayOfWeek                5000 non-null   int64
 52  ArrivalMonth                    5000 non-null   int64
 53  OccupancyRateBin                5000 non-null   object
 54  ProvidersOnShiftBin             5000 non-null   object
 55  NursesOnShiftBin                5000 non-null   object
 56  StaffPatientRatioBin            5000 non-null   object
dtypes: bool(2), datetime64[ns](12), float64(13), int64(10), object(20)
memory usage: 2.1+ MB

In [26]:
cols = [
    'RegistrationWaitTimeTime',
    'CheckInToNurseTime',
    'TriageToProviderStartTime',
    'ConsultationDurationTime',
    'TotalTimeInHospital'
]
# bỏ giá trị âm
for col in cols:
    df = df[df[col] >= 0]

# bỏ outlier trên
for col in cols:
    df = df[df[col] < df[col].quantile(0.99)]

In [27]:
df.head(10)

,PatientID,AgeGroup,Department,AppointmentType,InsuranceType,ArrivalMethod,VisitDate,AppointmentTime,ActualArrivalTime,CheckInTime,...,TestsToDischargeTime,TotalTimeInHospital,TotalDelayTime,ArrivalHour,ArrivalDayOfWeek,ArrivalMonth,OccupancyRateBin,ProvidersOnShiftBin,NursesOnShiftBin,StaffPatientRatioBin
0,P100000,Adult (36-60),Orthopedics,New Patient,Private,Walk-in,2024-03-15,NaT,2024-03-15 13:32:00,NaT,...,71.066667,151.750000,123.766667,13,4,3,Low,"(5.0, 7.0]","(12.0, 15.0]","(0.2, 0.3]"
3,P100003,Adult (36-60),Emergency,Urgent Care,Unknown,Emergency,2024-03-27,NaT,2024-03-27 10:59:00,NaT,...,13.183333,37.183333,37.116667,10,2,3,Low,"(3.0, 5.0]","(2.999, 6.0]","(0.3, 0.4]"
5,P100005,Adult (36-60),Radiology,Specialist Referral,Unknown,Walk-in,2024-03-29,NaT,2024-03-29 15:50:00,NaT,...,76.066667,151.750000,141.816667,15,4,3,Medium,"(5.0, 7.0]","(6.0, 9.0]","(0.3, 0.4]"
10,P100010,Young Adult (18-35),Pediatrics,Follow-up,Private,Walk-in,2024-02-20,NaT,2024-02-20 11:33:00,NaT,...,64.833333,198.500000,186.583333,11,1,2,Medium,"(1.999, 3.0]","(2.999, 6.0]","(0.2, 0.3]"
17,P100017,Adult (36-60),Pediatrics,Specialist Referral,Unknown,Walk-in,2024-01-15,NaT,2024-01-15 15:16:00,NaT,...,15.766667,93.750000,65.533333,15,0,1,Low,"(3.0, 5.0]","(2.999, 6.0]","(0.4, 0.5]"
18,P100018,Adult (36-60),Neurology,New Patient,Unknown,Walk-in,2024-02-26,NaT,2024-02-26 08:42:00,NaT,...,90.966667,277.833333,260.666667,8,0,2,High,"(1.999, 3.0]","(6.0, 9.0]","(0.2, 0.3]"
19,P100019,Pediatric (0-17),Orthopedics,Urgent Care,Private,Emergency,2024-02-02,NaT,2024-02-02 11:20:00,NaT,...,8.383333,100.166667,90.350000,11,4,2,High,"(3.0, 5.0]","(12.0, 15.0]","(0.099, 0.2]"
22,P100022,Adult (36-60),Pediatrics,New Patient,Medicaid,Walk-in,2024-03-25,NaT,2024-03-25 09:43:00,NaT,...,11.916667,90.383333,118.466667,9,0,3,Low,"(3.0, 5.0]","(12.0, 15.0]","(0.099, 0.2]"
25,P100025,Adult (36-60),Oncology,Urgent Care,Private,Walk-in,2024-03-29,NaT,2024-03-29 16:36:00,NaT,...,51.583333,114.016667,105.916667,16,4,3,Medium,"(1.999, 3.0]","(2.999, 6.0]","(0.099, 0.2]"
32,P100032,Senior (61+),Pediatrics,Specialist Referral,Unknown,Walk-in,2024-03-24,NaT,2024-03-24 16:08:00,NaT,...,120.216667,161.833333,155.583333,16,6,3,Very High,"(5.0, 7.0]","(2.999, 6.0]","(0.2, 0.3]"

In [28]:
df.describe()

,VisitDate,AppointmentTime,ActualArrivalTime,CheckInTime,TriageCompleteTime,ProviderStartTime,ProviderEndTime,TestsCompleteTime,DischargeTime,FacilityOccupancyRate,...,NurseToTriageCompleteTime,TriageToProviderStartTime,ConsultationDurationTime,ProviderEndToTestsCompleteTime,TestsToDischargeTime,TotalTimeInHospital,TotalDelayTime,ArrivalHour,ArrivalDayOfWeek,ArrivalMonth
count,1068,0,1068,0,0,0,0,0,1068,1068.000000,...,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000
mean,2024-02-15 09:02:01.348314624,NaT,2024-02-15 21:15:55.000000256,NaT,NaT,NaT,NaT,NaT,2024-02-15 23:56:40.786516736,0.624195,...,3.796052,48.798627,18.169944,38.198112,44.925421,160.758801,150.324438,11.733146,2.937266,2.014981
min,2024-01-01 00:00:00,NaT,2024-01-01 09:01:00,NaT,NaT,NaT,NaT,NaT,2024-01-01 10:01:00,0.300000,...,1.988871,1.000000,5.000000,0.000000,2.000000,28.350000,2.016667,7.000000,0.000000,1.000000
25%,2024-01-23 00:00:00,NaT,2024-01-23 09:37:30,NaT,NaT,NaT,NaT,NaT,2024-01-23 12:45:30,0.460000,...,2.803778,17.725000,11.945833,0.000000,9.979167,107.525000,100.195833,10.000000,1.000000,1.000000
50%,2024-02-15 12:00:00,NaT,2024-02-16 01:09:00,NaT,NaT,NaT,NaT,NaT,2024-02-16 03:41:00,0.620000,...,3.655554,36.266667,17.475000,33.416667,23.425000,156.716667,147.291667,12.000000,3.000000,2.000000
75%,2024-03-09 00:00:00,NaT,2024-03-09 14:53:45,NaT,NaT,NaT,NaT,NaT,2024-03-09 16:40:45,0.790000,...,4.757265,68.166667,23.920833,56.429167,78.762500,204.425000,195.987500,14.000000,5.000000,3.000000
max,2024-03-31 00:00:00,NaT,2024-03-31 16:35:00,NaT,NaT,NaT,NaT,NaT,2024-03-31 18:55:00,0.950000,...,5.990441,217.783333,40.200000,211.666667,135.366667,347.733333,339.033333,16.000000,6.000000,3.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.188230,...,1.140589,41.181655,8.528328,36.806012,40.789487,67.711440,68.705470,2.617608,1.989381,0.834900

In [29]:
time_cols = [
    'ArrivalDelayTime',
    'RegistrationWaitTimeTime',
    'RegistrationToCheckInTime',
    'CheckInToNurseTime',
    'NurseToTriageCompleteTime',
    'TriageToProviderStartTime',
    'ConsultationDurationTime',
    'ProviderEndToTestsCompleteTime',
    'TestsToDischargeTime',
    'TotalTimeInHospital',
    'TotalDelayTime'
]

df[time_cols].describe()

,ArrivalDelayTime,RegistrationWaitTimeTime,RegistrationToCheckInTime,CheckInToNurseTime,NurseToTriageCompleteTime,TriageToProviderStartTime,ConsultationDurationTime,ProviderEndToTestsCompleteTime,TestsToDischargeTime,TotalTimeInHospital,TotalDelayTime
count,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000,1068.000000
mean,-10.434363,6.021664,-2.983071,3.832053,3.796052,48.798627,18.169944,38.198112,44.925421,160.758801,150.324438
std,14.848002,2.243807,2.505684,2.422714,1.140589,41.181655,8.528328,36.806012,40.789487,67.711440,68.705470
min,-61.083333,2.013675,-8.651963,0.000944,1.988871,1.000000,5.000000,0.000000,2.000000,28.350000,2.016667
25%,-20.716667,4.123678,-4.978407,1.987288,2.803778,17.725000,11.945833,0.000000,9.979167,107.525000,100.195833
50%,-9.600000,6.019589,-2.997685,3.520538,3.655554,36.266667,17.475000,33.416667,23.425000,156.716667,147.291667
75%,0.037500,7.954093,-0.991622,5.334501,4.757265,68.166667,23.920833,56.429167,78.762500,204.425000,195.987500
max,36.650000,9.879932,2.562362,11.928806,5.990441,217.783333,40.200000,211.666667,135.366667,347.733333,339.033333

In [30]:
df = df[df['RegistrationToCheckInTime'] >= 0]

In [31]:
df[time_cols].mean().sort_values(ascending=False)

TotalTimeInHospital               157.221223
TotalDelayTime                    148.650240
TriageToProviderStartTime          49.161751
TestsToDischargeTime               41.077458
ProviderEndToTestsCompleteTime     37.822422
ConsultationDurationTime           17.483573
NurseToTriageCompleteTime           3.849402
CheckInToNurseTime                  3.808872
RegistrationWaitTimeTime            3.008474
RegistrationToCheckInTime           1.009272
ArrivalDelayTime                   -8.570983
dtype: float64

In [32]:
df.groupby('ProvidersOnShift')['TriageToProviderStartTime'].mean()

ProvidersOnShift
2    60.568056
3    48.818421
4    53.553509
5    44.873188
6    44.104545
7    68.443939
8    29.702273
Name: TriageToProviderStartTime, dtype: float64

In [33]:
df.groupby('OccupancyRateBin')['TotalTimeInHospital'].mean()

OccupancyRateBin
High         146.944000
Low          166.859259
Medium       150.040079
Very High    163.098148
Name: TotalTimeInHospital, dtype: float64

In [34]:
df.groupby('ArrivalHour')['TriageToProviderStartTime'].mean()

ArrivalHour
7     59.426667
8     47.928788
9     42.246296
10    47.573611
11    41.340278
12    48.635185
13    52.658974
14    44.976786
15    56.879365
16    59.280952
Name: TriageToProviderStartTime, dtype: float64

In [35]:
unique_triage = df['TriageCategory'].unique()
unique_reason = df['ReasonForVisit'].unique()
unique_tests = df['TestsOrdered'].unique()
unique_consult = df['ConsultationNeeded'].unique()

# In ra kết quả
print("Unique TriageCategory:", unique_triage)
print("Unique ReasonForVisit:", unique_reason)
print("Unique TestsOrdered:", unique_tests)
print("Unique ConsultationNeeded:", unique_consult)

Unique TriageCategory: ['Non-urgent' 'Semi-urgent' 'Emergency' 'Urgent' 'Immediate']
Unique ReasonForVisit: ['Chronic condition' 'Prescription renewal' 'Consultation'
 'Diagnostic testing' 'Injury' 'Routine checkup' 'Vaccination'
 'Follow-up procedure' 'Post-operative' 'Acute illness']
Unique TestsOrdered: ['CT scan' 'No Test' 'ECG' 'Basic labs' 'X-ray' 'Multiple tests'
 'Comprehensive labs' 'Ultrasound' 'MRI' 'Stress test' 'Biopsy']
Unique ConsultationNeeded: [ True False]

In [36]:
print(df['TriageCategory'].value_counts())

TriageCategory
Non-urgent     48
Semi-urgent    45
Urgent         29
Emergency      15
Immediate       2
Name: count, dtype: int64